#!/bin/sh

# Check if user is root on Arch distro. Install dialog.
pacman --noconfirm --needed -Sy dialog || error "Are you sure you're running this as the root user, are on an Arch-based distribution and have an internet connection?"

# Welcome user and pick dotfiles.
welcomemsg || error "User exited."

# Get and verify username and password.
getuserandpass || error "User exited."

# Give warning if user already exists.
usercheck || error "User exited."

# Last chance for user to back out before install.
preinstallmsg || error "User exited."

### The rest of the script requires no user input.

# Refresh Arch keyrings.
refreshkeys || error "Error automatically refreshing Arch keyring. Consider doing so manually."



-----------------------------------------------------------
pacman --noconfirm -S archlinux-keyring 
pacman --noconfirm --needed -S curl ca-certificates base-devel git ntp zsh
ntpdate 0.us.pool.ntp.org
git clone --depth 1 "https://aur.archlinux.org/yay-bin.git
cd yay-bin
makepkg --noconfirm -si
#aurinstall
yay -S --noconfirm  lf-git gtk-theme-arc-gruvbox-git   brave-bin sc-im  abook zsh-fast-syntax-highlighting-git task-spooler simple-mtpfs htop-vim-git mutt-wizard-git
#gitmakeinstall
git clone --depth 1 "https://github.com/LukeSmithxyz/dwm.git" 
cd "dwm" || exit 1
	make 
	make install 
  
https://github.com/LukeSmithxyz/dwmblocks.git
https://github.com/lukesmithxyz/dmenu.git
https://github.com/lukesmithxyz/st.git
https://github.com/lukesmithxyz/dwm.git

pacman --noconfirm --needed -S xorg-server
xorg-xwininfo
xorg-xinit
ttf-linux-libertine 
bc
xcompmgr
xorg-xprop
arandr
dosfstools
libnotify
dunst
exfat-utils
sxiv
xwallpaper
ffmpeg
gnome-keyring
neovim
mpd
mpc
mpv
man-db
ncmpcpp
newsboat
noto-fonts-emoji
ntfs-3g
pipewire
pipewire-pulse
pulsemixer
pamixer
maim
unclutter
unrar
unzip
lynx
xcape
xclip
xdotool
xorg-xdpyinfo
youtube-dl
zathura
zathura-pdf-mupdf
poppler
mediainfo
atool
fzf
highlight
xorg-xbacklight
slock
socat
moreutils

paru -S libxft-bgra-git



# Most important command! Get rid of the beep!
rmmod pcspkr
echo "blacklist pcspkr" > /etc/modprobe.d/nobeep.conf 

# Make zsh the default shell for the user.
chsh -s /bin/zsh "$name" >/dev/null 2>&1
sudo -u "$name" mkdir -p "/home/$name/.cache/zsh/"


# Tap to click
[ ! -f /etc/X11/xorg.conf.d/40-libinput.conf ] && printf 'Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
	# Enable left mouse button by tapping
	Option "Tapping" "on"
EndSection' > /etc/X11/xorg.conf.d/40-libinput.conf

# Fix fluidsynth/pulseaudio issue.
grep -q "OTHER_OPTS='-a pulseaudio -m alsa_seq -r 48000'" /etc/conf.d/fluidsynth ||
	echo "OTHER_OPTS='-a pulseaudio -m alsa_seq -r 48000'" >> /etc/conf.d/fluidsynth

# Start/restart PulseAudio.
pkill -15 -x 'pulseaudio'; sudo -u "$name" pulseaudio --start

# Last message! Install complete!

clear

 
